apiVersion: v1
kind: Service
metadata:
  name: tigerbeetle
  namespace: tigerbeetle
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: tigerbeetle
  type: LoadBalancer # Use NodePort or ClusterIP if external access is not needed
