apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tigerbeetle
  namespace: tigerbeetle
spec:
  serviceName: "tigerbeetle"
  replicas: 2 # Number of replicas (nodes) in the TigerBeetle cluster
  selector:
    matchLabels:
      app: tigerbeetle
  template:
    metadata:
      labels:
        app: tigerbeetle
    spec:
      containers:
        - name: tigerbeetle
          image: ghcr.io/tigerbeetle/tigerbeetle:latest
          securityContext:
            allowPrivilegeEscalation: true # Enables 'seccomp=unconfined'
          # command: ["/bin/sh", "-c"]
          # args:
          #   - |
          #     if [ ! -f /data/0_$(hostname | sed 's/.*-//').tigerbeetle ]; then
          #       /usr/local/bin/tigerbeetle format --cluster=0 --replica=$(hostname | sed 's/.*-//') --replica-count=2 /data/0_$(hostname | sed 's/.*-//').tigerbeetle;
          #     fi;
          #     exec /usr/local/bin/tigerbeetle start --addresses=0.0.0.0:3000 --directory=/data
          command:
            - "/usr/local/bin/tigerbeetle"
          args:
            - "format"
            - "--cluster=0"
            - "--replica=$(hostname | sed 's/.*-//')" # Extracts the pod ordinal (0, 1, 2, etc.)
            - "--replica-count=2" # Total number of replicas in the cluster
            - "/data/0_$(hostname | sed 's/.*-//').tigerbeetle" # Path to the data file within the container
          ports:
            - containerPort: 3000 # Expose TigerBeetle's default port
          volumeMounts:
            - name: tigerbeetle-pvc # Mounts the existing PVC to the /data directory
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: tigerbeetle-pvc # Reference to the claim name
      spec:
        accessModes:
          - ReadWriteOnce # Each pod gets its own dedicated storage
        resources:
          requests:
            storage: 128Mi # Adjust storage as needed (for testing)
